1) Create a Numpy array

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


2)Access and manipulated elements in the array

In [ ]:
#accessing element from the array
arr1[2]

3

In [ ]:
#change an element from the array 
arr1[2]=6
arr1


array([1, 2, 6])

3) Create 2 dimensional array and check the shape of the array

In [ ]:
#create a 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


4) Access elments from the 2D array using index positions

In [ ]:
#Acessing elements from the array
print(arr2 [0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


5)Create an Array of the type String


In [ ]:
#Array of type String
arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [ ]:
arr3[1]

'China'

6) Using the arrange() and inspace() function to evenly space values in a specified interval

In [ ]:

#array of events spaced in a specified interval
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
#Array of evenly spaced number in specified interval
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


7)Create an array of random values  between 0 & 1 in a given shape

In [ ]:
#Array of random values between 0 & 1 in a shape 
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.60126763 0.14514082 0.54080688 0.24735322 0.27131042 0.26038702
 0.38626394 0.18645157 0.13692119 0.65115748]


[[0.91936564 0.41851258 0.61060037 0.0848881 ]
 [0.78016389 0.69773356 0.15052515 0.02202139]
 [0.55070461 0.67894108 0.32101487 0.06677591]]


8)Create an array of constant in a given shape 

In [ ]:
#array of constant in a given shape
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9)Repeat each element of an array by a specified no. of time using repeat() & tile()function


In [ ]:
#create an array by repetetion
#repeat each element
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
#repeat an array by a specified no.of times 
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10)create an identity matrix using eye() and identity() function


In [ ]:
#create an identity matrix
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11) create a 5X5 2D array for random number between 0 & 1


In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.84898951 0.5826887  0.6765025  0.92182845 0.68651401]
 [0.51237014 0.4634848  0.5725569  0.19902274 0.5735808 ]
 [0.28575459 0.19924849 0.81179643 0.99511703 0.37899055]
 [0.14941157 0.37702895 0.14196667 0.38024536 0.72583141]
 [0.50850983 0.02354193 0.03095325 0.48211004 0.28430137]]


12) Sum an array along the row

In [ ]:
#sum along the row
print(np.sum(arr,axis=0))

[2.30503564 1.64599287 2.23377575 2.97832362 2.64921813]


13) sum an array along row


In [ ]:
#sum along the row
print(np.sum(arr,axis=1))

[3.71652317 2.32101538 2.67090709 1.77448396 1.32941641]


14)Calculate the mean ,median,standard deviation and variance

In [ ]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.4724938405267137
0.48211003767081084
0.2664733236927375
0.07100803223985447


15) Sort an array along the row using the sort() function


In [ ]:
#sort an array
arr=np.random.rand(5,5)
print(arr)

[[0.68465734 0.64995294 0.93856699 0.44213859 0.26293833]
 [0.92738528 0.98339578 0.94408127 0.10804011 0.69233612]
 [0.75104134 0.08116805 0.44836576 0.71075545 0.70989592]
 [0.07392673 0.19902037 0.60968691 0.44197431 0.03992351]
 [0.02983814 0.48407779 0.94675881 0.90279496 0.07233772]]


In [ ]:
#sort along the row
print(np.sort(arr,axis=1))

[[0.26293833 0.44213859 0.64995294 0.68465734 0.93856699]
 [0.10804011 0.69233612 0.92738528 0.94408127 0.98339578]
 [0.08116805 0.44836576 0.70989592 0.71075545 0.75104134]
 [0.03992351 0.07392673 0.19902037 0.44197431 0.60968691]
 [0.02983814 0.07233772 0.48407779 0.90279496 0.94675881]]


16) Append element to an arrayusing the append function

In [ ]:
#append element to an array
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


17)delete multiple elements in an array

In [ ]:
#delete multiply elements
arr2=np.array([4,5,6,7,8,9,10,11])
print(arr2)
print("\n")
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  8  9 10 11]


[ 4  6  7  9 10 11]


18.Concatenate element from 2 array

In [ ]:
#combine and split an array
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
